/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AnimeService } from "../anime.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AnimeCreateInput } from "./AnimeCreateInput";
import { AnimeWhereInput } from "./AnimeWhereInput";
import { AnimeWhereUniqueInput } from "./AnimeWhereUniqueInput";
import { AnimeFindManyArgs } from "./AnimeFindManyArgs";
import { AnimeUpdateInput } from "./AnimeUpdateInput";
import { Anime } from "./Anime";
import { SeasonFindManyArgs } from "../../season/base/SeasonFindManyArgs";
import { Season } from "../../season/base/Season";
import { SeasonWhereUniqueInput } from "../../season/base/SeasonWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AnimeControllerBase {
  constructor(
    protected readonly service: AnimeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Anime })
  @nestAccessControl.UseRoles({
    resource: "Anime",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: AnimeCreateInput): Promise<Anime> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        episodesCount: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Anime] })
  @ApiNestedQuery(AnimeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Anime",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Anime[]> {
    const args = plainToClass(AnimeFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        episodesCount: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Anime })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Anime",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: AnimeWhereUniqueInput
  ): Promise<Anime | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        episodesCount: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Anime })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Anime",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: AnimeWhereUniqueInput,
    @common.Body() data: AnimeUpdateInput
  ): Promise<Anime | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          episodesCount: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Anime })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Anime",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: AnimeWhereUniqueInput
  ): Promise<Anime | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          episodesCount: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/seasons")
  @ApiNestedQuery(SeasonFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Season",
    action: "read",
    possession: "any",
  })
  async findManySeasons(
    @common.Req() request: Request,
    @common.Param() params: AnimeWhereUniqueInput
  ): Promise<Season[]> {
    const query = plainToClass(SeasonFindManyArgs, request.query);
    const results = await this.service.findSeasons(params.id, {
      ...query,
      select: {
        anime: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/seasons")
  @nestAccessControl.UseRoles({
    resource: "Anime",
    action: "update",
    possession: "any",
  })
  async connectSeasons(
    @common.Param() params: AnimeWhereUniqueInput,
    @common.Body() body: SeasonWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      seasons: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/seasons")
  @nestAccessControl.UseRoles({
    resource: "Anime",
    action: "update",
    possession: "any",
  })
  async updateSeasons(
    @common.Param() params: AnimeWhereUniqueInput,
    @common.Body() body: SeasonWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      seasons: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/seasons")
  @nestAccessControl.UseRoles({
    resource: "Anime",
    action: "update",
    possession: "any",
  })
  async disconnectSeasons(
    @common.Param() params: AnimeWhereUniqueInput,
    @common.Body() body: SeasonWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      seasons: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
