/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateAnimeArgs } from "./CreateAnimeArgs";
import { UpdateAnimeArgs } from "./UpdateAnimeArgs";
import { DeleteAnimeArgs } from "./DeleteAnimeArgs";
import { AnimeCountArgs } from "./AnimeCountArgs";
import { AnimeFindManyArgs } from "./AnimeFindManyArgs";
import { AnimeFindUniqueArgs } from "./AnimeFindUniqueArgs";
import { Anime } from "./Anime";
import { SeasonFindManyArgs } from "../../season/base/SeasonFindManyArgs";
import { Season } from "../../season/base/Season";
import { AnimeService } from "../anime.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Anime)
export class AnimeResolverBase {
  constructor(
    protected readonly service: AnimeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Anime",
    action: "read",
    possession: "any",
  })
  async _animeItemsMeta(
    @graphql.Args() args: AnimeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Anime])
  @nestAccessControl.UseRoles({
    resource: "Anime",
    action: "read",
    possession: "any",
  })
  async animeItems(@graphql.Args() args: AnimeFindManyArgs): Promise<Anime[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Anime, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Anime",
    action: "read",
    possession: "own",
  })
  async anime(
    @graphql.Args() args: AnimeFindUniqueArgs
  ): Promise<Anime | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Anime)
  @nestAccessControl.UseRoles({
    resource: "Anime",
    action: "create",
    possession: "any",
  })
  async createAnime(@graphql.Args() args: CreateAnimeArgs): Promise<Anime> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Anime)
  @nestAccessControl.UseRoles({
    resource: "Anime",
    action: "update",
    possession: "any",
  })
  async updateAnime(
    @graphql.Args() args: UpdateAnimeArgs
  ): Promise<Anime | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Anime)
  @nestAccessControl.UseRoles({
    resource: "Anime",
    action: "delete",
    possession: "any",
  })
  async deleteAnime(
    @graphql.Args() args: DeleteAnimeArgs
  ): Promise<Anime | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Season], { name: "seasons" })
  @nestAccessControl.UseRoles({
    resource: "Season",
    action: "read",
    possession: "any",
  })
  async resolveFieldSeasons(
    @graphql.Parent() parent: Anime,
    @graphql.Args() args: SeasonFindManyArgs
  ): Promise<Season[]> {
    const results = await this.service.findSeasons(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
