// <auto-generated />
using BetterDocs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BetterDocs.Migrations
{
    [DbContext(typeof(DocumentsDbContext))]
    [Migration("20191204001918_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1");

            modelBuilder.Entity("BetterDocs.Data.Entities.TextDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContributorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TextDocuments");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ContributorId = "7993615d-93bf-4e07-9b4f-a193e55cf1a9",
                            OwnerId = "7993615d-93bf-4e07-9b4f-a193e55cf1a9",
                            Text = "empty"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
